title: BAIN?!
author: K.K.Buhler
email: karin.buehler@stud.fhgr.ch
description: > # this means to ignore newlines until "baseurl:"
  Fragen und Antworten zu Bibliotheks- und Archivinformatik


show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-slate 
